name: Compile with SourceMod

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install curl p7zip-full p7zip-rar

      - name: Set environment variables
        run: |
          git fetch --unshallow
          VERSION=$(git rev-list --count HEAD)
          SHORT=$(git describe --always --long --dirty)
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo "GIT_COMMIT=$VERSION" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=${{ matrix.SM_VERSION }}.$VERSION.$SHORT" >> $GITHUB_ENV
          echo "SOURCEMOD_PATH=$SOURCEMOD_PATH" >> $GITHUB_ENV
          echo "SCRIPTS_PATH=$SOURCEMOD_PATH/scripting" >> $GITHUB_ENV
          echo "PLUGINS_PATH=$SOURCEMOD_PATH/plugins" >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Set HexTags version
        run: |
          sed -i "s/<VERSION>/$PLUGIN_VERSION/g" $SCRIPTS_PATH/hextags.sp

      - name: Compile HexTags
        run: |
          spcomp -i $includePath -i $SCRIPTS_PATH/include hextags.sp
        working-directory: ${{ env.SCRIPTS_PATH }}/

      - name: Move compiled plugins
        run: |
          rm -rf $PLUGINS_PATH
          mkdir -p $PLUGINS_PATH/
          rsync -av --include='*/' --include="*.smx" --exclude="*" --prune-empty-dirs --remove-source-files $SCRIPTS_PATH/ $PLUGINS_PATH/

      - name: Move addons to build
        run: |
          mkdir build
          mv ./addons build/

      - name: Add LICENSE to build package
        run: |
          mv $GITHUB_WORKSPACE/LICENSE .
        working-directory: ./build

      - name: Remove unnecessary files and folders from build
        run: |
          rm -rf addons/sourcemod/scripting
          rm -rf addons/sourcemod/configs/{*.cfg,*.ini}
        working-directory: ./build
      
      - name: Compress package
        run: |
          zip -9rq HexTags-${{ env.PLUGIN_VERSION }}.zip build/*

      - uses: actions/upload-artifact@v3
        with:
          name: HexTags-${{ env.PLUGIN_VERSION }}
          path: HexTags-${{ env.PLUGIN_VERSION }}.zip
